spring.datasource.url=jdbc:sqlserver://democrazy.database.windows.net:1433;database=democrazy;user=democrate@democrazy;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=democrate
spring.datasource.password=9G2pES6{31]%9Z6-LXHL3v